[package]
name = "wyrm"
version = "0.1.0"
authors = ["maciejkula <maciej.kula@gmail.com>"]
license = "MIT"

[dependencies]
ndarray = { version = "0.10.13", features = ["serde-1"] }
rand = "0.3.18"
smallvec = { version = "0.5.0", features = ["serde"] }
itertools = "0.7.3"
rayon = "0.9.0"
serde = { version = "1.0.24", features = ["rc"] }
serde_derive = "1.0.24"
stdsimd = "0.0.3"

[profile.bench]
lto = true
debug = true

[profile.release]
lto = true