[package]
name = "wyrm"
version = "0.6.0"
authors = ["Maciej Kula"]
license = "MIT"
description = "A low-overhead, define-by-run autodifferentiation library."
documentation = "https://docs.rs/wyrm/"
repository = "https://github.com/maciejkula/wyrm"
readme = "readme.md"

[badges]
travis-ci = { repository = "maciejkula/wyrm", branch = "master" }

[features]
fast-math = []

[dependencies]
ndarray = { version = "0.11.0", features = ["serde-1"] }
rand = "0.3.18"
smallvec = { version = "0.5.0", features = ["serde"] }
itertools = "0.7.3"
rayon = "0.9.0"
serde = { version = "1.0.24", features = ["rc"] }
serde_derive = "1.0.24"
stdsimd = "0.0.3"

[dev-dependencies]
ndarray = { version = "0.11.0", features = ["blas", "serde-1"] }
blas-src = { version = "0.1.2", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.5.6", default-features = false, features = ["static"] }

[profile.bench]
lto = true
debug = true

[profile.release]
lto = true